### ISSUE TITLE
As a webapp user I want that the beacon browsing becomes faster

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.beacon.admin#19]
The beacon administration web application, should implement a API-side pagination and caching mechanism to keep response times low also with the perspective of future huge data amounts. Browsing beacons with a table or map representation must be instant, that is, we would need to perform costly operation on the API directly and render graphical elements solely when they are needed.

- [ ] Test it with stress testing (API side)

**Comment by davidebz** [comment]
After performing some load test and profiling, the info request has a throughput of some request per seconds. Profiling the code results that the most of the time is spent by hibernate/database. See attached picture.

![performance](https://user-images.githubusercontent.com/4040194/71249785-431a2780-231e-11ea-91ff-d0ab25dca47f.png)
