### ISSUE TITLE
Add new beacon window doesn't close

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.beacon.admin#61]
Clicking on the "add new beacon" icon it opens the window "Add new beacon" but then it is impossible to close the window by clicking on the x or on any other point of the screen out of the window.

![Schermata da 2020-12-21 15-46-29](https://user-images.githubusercontent.com/7909989/102789558-9812d280-43a4-11eb-880a-15d05aa60e7d.png)

**Comment by noctho** [comment]
Fixed in the last pull request
