### ISSUE TITLE
Bug: Solution description is overwritten by solution title

### ISSUE THREAD

**Issue by niettadesantis** [noi-techpark/it.bz.beacon.admin#97]
After having inserted the solution to an issue, it seems that the text that was in the solution description is beeing overwritten by the one that was put into the title field.

![image](https://user-images.githubusercontent.com/46811227/185560276-02e5f911-ff7f-46d1-b2b5-63002364c828.png)

**Comment by sseppi** [comment]
I tested the feature and now seems to work fine. @niettadesantis can you please confirm that everything works fine also with your user?

**Comment by niettadesantis** [comment]
Ciao @sseppi,
purtroppo c'è ancora (avevo scritto "test description"):
![image](https://user-images.githubusercontent.com/46811227/195520673-6629db20-d57f-4427-920b-bf7e6cacbd7e.png)

**Comment by sseppi** [comment]
Hi @niettadesantis,
looking at your screenshot I noticed that you are using the production environment.
We put the changes only in testing. You cha use to following link to test and see the new functionalities:
https://admin.beacon.testingmachine.eu
The credentials should be the same as production.
Best

**Comment by niettadesantis** [comment]
Ok, I understand. As I reported this for the production and you didn't mentioned that it was solved in testing environment it wasn't clear for me.
On testing it works fine!

**Comment by sseppi** [comment]
OK, thank you for your help!
