### ISSUE TITLE
Some inputs for Beacon Admin webapp UX optimization.

### ISSUE THREAD

**Issue by niettadesantis** [noi-techpark/it.bz.beacon.admin#99]
Deadline: 31 October 2022

Here are some inputs from my side:
- If I am inside a beacon detail page, I don't want to go back to the "Beacons" page to be able to search with a new beacon ID. -> The search field in the top bar should be always active
- In the beacon list in the "Beacons" page, I want to see more details about the beacon, e.g. the POI name.
- I want to search not only with beacon ID but also with POI name
- When I'm in the map view and want to have more details of a beacon, I click on the pin on the map and are beeing redirected to the beacon detail page. I would like to have some few information (at least beacon ID and POI name) onmouseover on the pin or by displaying an overlay onclick (with a "more" link inside, that finally sends me to the detail page).

As said in the meeting with ARO, the main new features of the issue-section of the webapp should be:
- I want to get a notification if someone answers the issue that I inserted
- I want to be able to insert comments, not only issues and their resolvings
- I want to be able to edit and/or delete the issues and comments that I insert
- I want that in the issues list I see who reported it
- I want that the issues list gives me a filter to be able to view also the closed issues
- I want that in the issues list I see the status of the issue

Feel free to add more features if I forgot some, @sseppi

**Comment by noctho** [comment]
@niettadesantis Can you please send us a wish list of the field you will have in the list view and in the map view.

**Comment by sseppi** [comment]
Hi @niettadesantis ,
we put all the new feature in testing at the following link:
https://admin.beacon.testingmachine.eu
I tested it and in my point of view is everything fine now. Can you plese provide us your feedback too?

@davidebz and @noctho maybe we could add in the list view also the "last seen" field?

**Comment by niettadesantis** [comment]
Everything fine for me.
What is the "last seen" field for, @sseppi?

**Comment by sseppi** [comment]
Hi @niettadesantis ,
we have two different values that allows us to understand if a beacon is working:
- _Trusted updated_: is the last time that the beacon has been seen by an app that is able to read the battery status and make the update;
- _Last Seen_: is the last time that we received through our APIs a request of information/data about a beacon.

Did I clarified?

**Comment by niettadesantis** [comment]
> * _Trusted updated_: is the last time that the beacon has been seen by an app that is able to read the battery status and make the update;
> * _Last Seen_: is the last time that we received through our APIs a request of information/data about a beacon.

Can it be that it's the opposite?
This beacon of Castelfeder has been seen by the Südtirol Guide the last time in April. I guess that's the "Trusted update".
"Last seen" is of 2019: so that seems to be the last time it was checked with the beacon admin app... am I right?
![image](https://user-images.githubusercontent.com/46811227/195525338-d0baa351-9f00-49d5-95b6-31e6bd670486.png)

**Comment by sseppi** [comment]
> > * _Trusted updated_: is the last time that the beacon has been seen by an app that is able to read the battery status and make the update;
> > * _Last Seen_: is the last time that we received through our APIs a request of information/data about a beacon.
> 
> Can it be that it's the opposite? This beacon of Castelfeder has been seen by the Südtirol Guide the last time in April. I guess that's the "Trusted update". "Last seen" is of 2019: so that seems to be the last time it was checked with the beacon admin app... am I right? ![image](https://user-images.githubusercontent.com/46811227/195525338-d0baa351-9f00-49d5-95b6-31e6bd670486.png)

We had a bug here, that we solved with the last iteration.
In any case the Südtirol Guide has the rights to read the battery status of the beacon.
This means that the Südtirol Guide does always a trusted update.
